apiVersion: v1
kind: Service
metadata:
  name: banking-app-service
spec:
  type: NodePort
  selector:
    app: banking-app
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30080
      protocol: TCP
